### ISSUE TITLE
Error on link, missing libfl.so

### ISSUE THREAD

**Issue by rvnash** [nrobinson2000/neopo#10]
**Describe the bug**
While compiling my project I get the error described below.

**To Reproduce**
In my project I do "neopo compile" and the following error occurs. A compile using the cloud particle-cli does not produce any problems. If you require all my code to observe this yourself, I will provided.

**Screenshots**

![image](https://user-images.githubusercontent.com/182201/88589372-071f1180-d027-11ea-8665-5b79120c77a9.png)

**Desktop (please complete the following information):**
 - OS: raspberrypi 4

**Comment by nrobinson2000** [comment]
I did some quick googling and it looks like libfl.so is part of the libfl-dev package. Try installing the package and then compile again.

```
sudo apt install libfl-dev
```

**Comment by rvnash** [comment]
That did it!

[image: image.png]

Thanks so much. I'm going to start giving your project here a test drive. I
really like the fact that it interoperates with the VSC Workbench.

Thanks again,
- Richard Nash

**Comment by nrobinson2000** [comment]
Great to hear! I’ll add libfl-dev to the Raspberry Pi apt dependencies in install.sh.

**Comment by nrobinson2000** [comment]
@rvnash I‘ve added support for deviceOS 2.0.0 and gcc-arm 9.2.1 recently. Hope you find it useful.

**Comment by rvnash** [comment]
Thanks Nathon,

Good stuff you've got going here, and I appreciate that you are sharing it
with the community.

- Richard Nash
