### ISSUE TITLE
Errors while installing on MacOS

### ISSUE THREAD

**Issue by mf42** [nrobinson2000/neopo#14]
Thx for that project. I've been working a long while with po-util and really loved it; 
seems that there is an Issue with Apple SIP (...?)

**Describe the bug**
installation on MacOS is terminated with error

copying man/neopo.1 -> /usr/share/man/man1
    error: could not create '/usr/share/man/man1/neopo.1': Operation not permitted

**To Reproduce**
bash <(curl -sL neopo.xyz/install)

same problem with installation via pip...

**Expected behavior**
clear installation

**Screenshots**

**Desktop (please complete the following information):**
MacOS 11.4 Big Sur 

**Additional context**
M1 Chip
Python 3.9 installed, latest Version (via brew)
local Particle CLI for maintaining local Particle Server

**Comment by nrobinson2000** [comment]
Hey @mf42,

Thanks for using po-util and neopo.

I personally haven't tested on macOS Big Sur since I keep my 2016 macbook pro on macOS Mojave and I use Arch Linux, Manjaro, Debian, and Raspbian on my other machines.

When installing neopo as root, it will attempt to install additional files like the manpage as you can see in the error you encountered. https://github.com/nrobinson2000/neopo/blob/master/setup.py#L29

If you try to install neopo with pip without using `sudo` it should't try to install the additional files.


```bash
git clone https://github.com/nrobinson2000/neopo
cd neopo
python3 -m pip install .
```

**Comment by mf42** [comment]
Hi @nrobinson2000,

thank you for your quick reply.
Ok, git clone ... worked fine but still I've a prob with pip:

> dev@MacBook-Pa neopo % python3 -m pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /Users/dev/neopo
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Building wheels for collected packages: neopo
  Building wheel for neopo (setup.py) ... done
  Created wheel for neopo: filename=neopo-334.970c5fd-py3-none-any.whl size=28666 sha256=f4c2e9fd74ef3d5e1390f48fce8b09756c2bbfe63c0fdc5e217c97bcafef6d25
  Stored in directory: /private/var/folders/p1/cct7mlx131s6m68t1w4_6jch0000gp/T/pip-ephem-wheel-cache-663qu9d3/wheels/83/45/4f/4de98c186b111f27a4bb44f9142145155a4afa9e2507c49681
  WARNING: Built wheel for neopo is invalid: Metadata 1.2 mandates PEP 440 version, but '334.970c5fd' is not
Failed to build neopo
Installing collected packages: neopo
  Attempting uninstall: neopo
    Found existing installation: neopo 334.970c5fd
    Uninstalling neopo-334.970c5fd:
      Successfully uninstalled neopo-334.970c5fd
    Running setup.py install for neopo ... done
  DEPRECATION: neopo was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Successfully installed neopo-334.970c5fd


as you can see there is an issue with building wheel. Sorry, Im not that deep in the topic...
My environment:

>dev@MacBook-Pa neopo % python --version
Python 3.9.5
dev@MacBook-Pa neopo % pip --version
pip 21.1.2 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
dev@MacBook-Pa neopo % 


Thank you for your help, Best

**Comment by nrobinson2000** [comment]
Hey @mf42,

I've just pushed a fix to change the version string to comply with PEP 440. Can you `git pull` and try installing now?

**Comment by mf42** [comment]
Hi @nrobinson2000,
just downloaded and reinstalled. The installation routine went through so that point is fine now. After running neopo create I received some fancy .py-Error messages but that is another issue. From that point of view we could close; Thank you for your help, Best
