### ISSUE TITLE
Invalid Firmware Version - neopo Docker

### ISSUE THREAD

**Issue by ajowsey** [nrobinson2000/neopo#22]
Specifically within docker neopo, Im getting the following error on all of my builds lately

Invalid deviceOS version 5.1.0!
Firmware related error!
Invalid firmware version!

I've literally reran successful bitbucket pipeline builds with exact configuration as before but now it fails.

**Comment by nrobinson2000** [comment]
Hey @ajowsey thanks for finding this!

It seems like the API for discovering the Particle Workbench VSIX changed slightly, so neopo was unable to obtain the manifest.json and particle executable.

I've fixed this by using a more reliable way to find the URL of the package in the following commit: https://github.com/nrobinson2000/neopo/commit/907b8d720dd0827bb25d07428f29017cfb2985c8

With the fix, neopo can now successfully obtain the manifest.json and download firmware again.

Unfortunately I don't have automatic builds for neopo on Docker Hub anymore, but I'll try to build and push an image soon.

**Comment by nrobinson2000** [comment]
I've built and pushed an image with the latest commit:
https://hub.docker.com/r/nrobinson2000/neopo/tags

**Comment by ajowsey** [comment]
Amazing work! Thanks @nrobinson2000!!!
