### ISSUE TITLE
[BUG] Error building on Linux

### ISSUE THREAD

**Issue by pierrep** [nrobinson2000/neopo#8]
**Describe the bug**
I am unable to build an existing Particle project. It looks like this is because of missing gcc-arm
```
$ neopo build
Traceback (most recent call last):
  File "/usr/local/sbin/neopo", line 943, in main
    commands[args[1]](args)
  File "/usr/local/sbin/neopo", line 677, in compile_command
    buildCommand("compile-user", 2, args)
  File "/usr/local/sbin/neopo", line 606, in buildCommand
    build(project, command, False, verbosity)
  File "/usr/local/sbin/neopo", line 523, in build
    compilerVersion, scriptVersion, toolsVersion, firmwareVersion = loadManifest(True)
  File "/usr/local/sbin/neopo", line 227, in loadManifest
    data["gcc-arm"],
KeyError: 'gcc-arm'
An unexpected error occurred!
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS

**Comment by pierrep** [comment]
FWIW, I get this when creating a new project as well.

**Comment by nrobinson2000** [comment]
Hey @pierrep,

This bug likely occurred because your `~/.neopo/cache/manifest.json` file was not populated correctly during installation because the Particle dependencies were likely already installed from Workbench. I will push a fix for this soon.

In the meantime, can you try doing a forced installation of dependencies?

```
$ neopo install -f
```

**Comment by nrobinson2000** [comment]
I have pushed a fix for this. It appears that when dependencies were skipped during the installation they were not added to manifest.json. I have corrected this behavior.

Upgrading neopo and installing dependencies without `-f` should fix your issue.

```bash
$ neopo upgrade
$ neopo install
```

**Comment by pierrep** [comment]
Excellent, I was hoping you'd be prompt and I wasn't disappointed! I'm highly in need of your "iterative" function to program multiple xenons. I was in the process of rolling my own then came across your project....this will save me a lot of time...thanks!

**Comment by pierrep** [comment]
OK I ran 
```
$ neopo upgrade
$ neopo install
```
and everything works fine now. I flashed 4 Xenons with a single 

`neopo iterate flash`

command. Huge thanks...I have around 35 devices, so this was critical to solve.

Just a couple of other random questions while I'm here.
I was using your [code](https://github.com/nrobinson2000/po/blob/master/depend/custom-baud/custom-baud.c) to enter DFU mode,  but it was only working by setting the baud to 14400 and then to 9600 again. Is that normal??

Also, I'd REALLY love a homebrew solution to OTA programming. I see that you've dug into the toolchain a fair bit....do you know if is this remotely feasible? If so, I'd love some pointers. It's more for the longer term as I'm making an art installation from my Xenons and it'll be a huge pain to reprogram them via USB once they are installed.

**Comment by nrobinson2000** [comment]
> I was using your code to enter DFU mode, but it was only working by setting the baud to 14400 and then to 9600 again. Is that normal??

On Linux I’ve seen this behavior when using that C program. I’ve had better luck using [pyserial](https://pythonhosted.org/pyserial/shortintro.html#opening-serial-ports).

However, lately with deviceOS you can use Particle CLI to put devices into DFU. I’ve included access to The Particle CLI executable used within neopo.

```
$ neopo particle usb dfu
```

**Comment by pierrep** [comment]
Yeah I'm aware of `particle usb dfu`, I currently have a shell alias for it. I was just wondering about that weird behaviour.

Thanks anyway...RPI's would defeat my low energy budget, and there's already an RPI solution [here](http://www.happybrackets.net/). I was just wondering how Particle do it through the Cloud, if there was any published info on that...but I'm guessing not.
