### ISSUE TITLE
[BUG] No such file or directory: '~/.neopo/cache/manifest.json'

### ISSUE THREAD

**Issue by toluschr** [nrobinson2000/neopo#9]
**Describe the bug**
Script throws python error

**To Reproduce**
1. `python3 <(curl -SL https://raw.githubusercontent.com/nrobinson2000/neopo/master/bin/install.py)`
2. `neopo create blink-led`
```
Initializing project in directory /mnt/data/particle/blink-led...
> A new project has been initialized in directory /mnt/data/particle/blink-led
Initialized empty Git repository in /mnt/data/particle/blink-led/.git/
Traceback (most recent call last):
  File "/home/tom/bin/neopo", line 947, in main
    commands[args[1]](args)
  File "/home/tom/bin/neopo", line 666, in create_command
    create(os.path.dirname(projectPath), os.path.basename(projectPath))
  File "/home/tom/bin/neopo", line 423, in create
    version = loadManifest(False)["deviceOS"]
  File "/home/tom/bin/neopo", line 220, in loadManifest
    with open(jsonFiles["manifest"], "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tom/.neopo/cache/manifest.json'
An unexpected error occurred!
To report this error on GitHub, please open an issue:
https://github.com/nrobinson2000/neopo/issues
```

**Expected behavior**
It works

**Desktop (please complete the following information):**
 - OS: Void Linux

**Comment by nrobinson2000** [comment]
I haven’t tested neopo on Void Linux, but I am glad to support it.

In order for neopo to work you need to install dependencies like gcc-arm, deviceOS, etc.

To install these dependencies run:

```
neopo install
```

`~/.neopo/cache/manifest.json` will be created during the installation.

Also, you will need to install some other dependencies with your package manager in order to get the compiler to work. Have a look at [the install.sh](https://github.com/nrobinson2000/neopo/blob/master/install.sh) to get an idea.

**Comment by toluschr** [comment]
@nrobinson2000 Thanks for the quick reply. I installed those dependencies manually using (`sudo xbps-install dfu-util python3 git vim libarchive-devel`). I overlooked the line containing `neopo install`. It now seems to work just fine!

**Comment by nrobinson2000** [comment]
Great to hear! I’ll add that to install.sh so anyone else on Void Linux can use the universal installer as well.

```
$ bash <(curl -sL neopo.xyz/install)
```

**Comment by toluschr** [comment]
It's probably `perl-Archive-Zip` instead of `libarchive-devel`. The script works without it though.

**Comment by nrobinson2000** [comment]
Interesting. The Particle makefile requires a`crc32` program and `perl-Archive-Zip` supplies that on other distros.

**Comment by toluschr** [comment]
It's the same on Void. I probably just haven't used the function that requires it yet.

**Comment by nrobinson2000** [comment]
@toluschr 

I whipped a Void Linux VM and I did some testing. To get `neopo build` working I had to install the packages you suggested as well as `void-repo-multilib glibc-32bit` in order to run 32-bit gcc-arm. I have added support for Void Linux in install.sh.
